---
title "Models2 classes"
---
classDiagram

  class AMedia {
    <<abstract>>
    + ELanguage : DEFAULT_LANGUAGE$
    + string : Id
    + EMediaType : MediaType
    + ELanguage : DefaultLanguage
    + DateOnly : DateAdded
    + DateOnly : CreationDate
    + int : CreationYear
    + string : Group
    + bool : IsGroupMember
    # MediaInfos : TMediaInfos
    # MediaSources : TMediaSources
    # MediaPictures : TMediaPictures
  }

  class IMediaInfosContainer {
    <<interface>>
    + MediaInfos : IMediaInfos
  }
  class IMediaSourcesContainer {
    <<interface>>
    + MediaSources : IMediaSources
  }
  class IMediaPicturesContainer {
    <<interface>>
    + MediaPictures : IMediaPictures
  }
  
  class IMediaSources {
    <<interface>>
    + GetDefaultMediaSource() : IMediaSource?
    + GetMediaSource(ELanguage) : IMediasource?
    + GetMediaSources() : IEnumerable~IMediaSource~
    + AddMediaSource(IMediaSource) : bool
    + RemoveMediaSource(IMediaSource) : bool
    + ClearMediasSources()
    + SetDefaultMediaSource(IMediaSource)
  }

  class IMediaSource {
    <<interface>>
    + DateOnly : DateAdded
    + DateOnly : CreationDate
    + int : CreationYear
    + string : Description
    + IListWithPrincipal~ELanguage~ : Languages
  }

  class IMediaSourcePhysical {
    <<interface>>
  }

  class IMediaSourceVirtual {
    <<interface>>
    + StorageRoot : string
    + StoragePath : string
    + FileName : string
    + FileExtension : string
    + FullFileName : string
    + Size : long
    + MediaStreams : IMediaStreams
  }

  class IMediaInfos {
      <<interface>>
    + GetDefaultMediaInfo() : IMediaInfo?
    + GetMediaInfo(ELanguage) : IMediaInfo?
    + GetMediaInfos() : IEnumerable~IMediaInfo~
    + AddMediaInfo(IMediaInfo)
    + RemoveMediaInfo(IMediaInfo)
    + ClearMediasInfos()
    + SetDefaultMediaInfo(IMediaInfo)
  }
  class IMediaInfo {
    <<interface>>
    + DateOnly : DateAdded
    + DateOnly : CreationDate
    + int : CreationYear
    + string : Description
    + IListWithPrincipal~ELanguage~ : Languages
    + List~string~ : Tags
  }

  class IMediaPictures {
    <<interface>>
    + GetDefaultMediaPicture() : IMediaPicture?
    + GetMediaPicture(ELanguage) : IMediaPicture?
    + GetMediaPictures() : IEnumerable~IMediaPicture~
    + AddMediaPicture(IMediaPicture) : bool
    + RemoveMediaPicture(IMediaPicture) : bool
    + ClearMediasPictures()
    + SetDefaultMediaPicture(IMediaPïcture)
  }

  class IMediaPicture {
    <<interface>>
  }

  class EMediaType {
    <<enum>>
    Unknown
    Movie
    Serie
    SerieSeason
    SerieEpisode
    Music
    Video
    Theatre
    Spectacle
    Concert
  }

  class ELanguage {
    Unknown
    French
    FrenchFrance
    FrenchQuebec
    FrenchBelgium
    English
    EnglishUs
    EnglishUk
    Chinese
    ChineseCantonese
    ChineseMandarin
    Japanese
    Korean
    German
    Dutch
  }

  class TMediaMovie {
  }

  class IMediaSourceProperties {
    <<interface>>
  }

  class IMediaInfosContainer {
    MediaInfos : IMediaInfos
  }

  class IMediaStream {
    <<interface>>
  }

  class AMediaStream {
    <<abstract>>
  }

  class TMediaStreamAudio {

  }
  class TMediaStreamVideo {

  }
  class TMediaStreamData {

  }
  class TMediaStreamSubTitle {

  }
  class TMediaStreamGeneric {

  }

  class IMediaStreams {
    <<interface>>
    + Add(params IMediaStreams[]) : bool
    + AddRange(IEnumerable~IMediaStream~) : bool
    + Get(int) : IMediaStream?
    + GetAll() : IEnumerable~IMediaStream~
    + Remove(IMediaStream) : bool
    + Clear()
    + Any() : bool
    + Any(Predicate~IMediaStream~) : bool
    + IsEmpty()
  }

  class TMediaStreams {
    + MediaStreamsVideo : IEnumerable~TMediaStreamVideo~
    + MediaStreamsAudio : IEnumerable~TMediaStreamAudio~
    + MediaStreamsSubTitle : IEnumerable~TMediaStreamSubTitle~
    + MediaStreamsData : IEnumerable~TMediaStreamData~
    + MediaStreamsGeneric : IEnumerable~TMediaStreamGeneric~
  }

AMedia "1" --> "0..n" IMediaSourcesContainer
AMedia "1" --> "1..n" IMediaInfosContainer
AMedia "1" --> "0..n" IMediaPicturesContainer
IMediaInfosContainer ..> IMediaInfos
IMediaSourcesContainer ..> IMediaSources
IMediaPicturesContainer ..> IMediaPictures
AMedia ..> EMediaType
TMediaMovie <|-- AMedia
IMediaSources ..> IMediaSource
IMediaSources ..> ELanguage
IMediaInfos ..> IMediaInfo
IMediaInfos ..> ELanguage
IMediaPictures ..> IMediaPicture
IMediaPictures ..> ELanguage
IMediaSource ..> IMediaSourceProperties
IMediaStreams ..> "0..n" IMediaStream
TMediaStreams <|-- IMediaStreams
TMediaStreams ..> "0..n" IMediaStream
AMediaStream <|-- IMediaStream
TMediaStreamAudio <|-- AMediaStream
TMediaStreamVideo <|-- AMediaStream
TMediaStreamSubTitle <|-- AMediaStream
TMediaStreamData <|-- AMediaStream
TMediaStreamGeneric <|-- AMediaStream

 IMediaSourceVirtual <|-- IMediaSource
 IMediaSourceVirtual "1" --> "1" IMediaStreams
 IMediaSourcePhysical <|-- IMediaSource